export const ROOT_PATH = '/'
export const PRODUCTS_PATH = '/products'
export const PRODUCT_PATH = '/product'
export const CART_PATH = '/cart'
export const LOGIN_PATH = '/login'
export const FAVORITES_PATH = 'favorites'
